name: Build and push manifest
on:
  workflow_call:
    inputs:
      image:
        description: 'Image name'
        required: true
        type: string
      tag:
        description: 'Tag name'
        required: true
        type: string 
      additional_tags:
        description: 'Additional tags'
        required: false
        type: string
        default: ''      
env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
jobs:
  manifest:
    name: Build and push manifest
    runs-on: databox-arm64
    timeout-minutes: 1
    steps:
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      - name: Additional tags
        id: docker-additional-tags
        uses: actions/github-script@v7
        with:
          debug: true
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          result-encoding: string
          script: |
            const tagsString = `${{ inputs.additional_tags }}`

            if (!tagsString) {
              return ' ';
            }

            const tags = tagsString.split(' ').filter(tag => tag.trim() !== '');
            const result = tags.map(tag => `  --amend ${{ env.ECR_REGISTRY }}/${{ inputs.image }}:${tag}`).join(' \\\n');
            
            return result.trim();

      - name: Build and push manifest
        run: |
          IMAGE="${{ env.ECR_REGISTRY }}/${{ inputs.image }}:${{ inputs.tag }}"    
          docker manifest create $IMAGE \
            ${{ steps.docker-additional-tags.outputs.result }}
          docker manifest push $IMAGE