name: Release Drafter

on: 
  workflow_call:
    inputs:
      target_branch:
        description: 'The default branch of the repository'
        required: true
        type: string
        default: 'master'

jobs:
  Draft-Release:
    runs-on: databox-arm64
    steps:
      - name: Release Drafter
        id: release-drafter
        uses: release-drafter/release-drafter@v6
        with:
          commitish: ${{ github.event.inputs.target_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}