name: Release Drafter

on: workflow_call

jobs:
  update_release_draft:
    runs-on: ubnutu-22-04-arm64-1-core-4-ram
    steps:
      # Drafts next Release notes as Pull Requests are merged into the main branch
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
