name: Release Drafter

on: workflow_call

jobs:
  Draft-Release:
    runs-on: databox-arm64
    steps:
      - name: Release Drafter
        id: release-drafter
        uses: release-drafter/release-drafter@v6
        with:
          commitish: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}