name: Pull Request Labels

on: workflow_call

jobs:
  label:
    runs-on: ubnutu-22-04-arm64-1-core-4-ram
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "major,minor,patch"
