name: Semgrep

on:
  workflow_call:

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: databox-amd64
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v6
      - run: semgrep scan --config auto --error
