name: Build and push image
on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag name'
        required: true
        type: string
    outputs:
      match:
        value: ${{ jobs.tag-filter.outputs.match }}
      
jobs:
  tag-filter:
    name: Tag ${{ inputs.tag }}
    runs-on: ubnutu-22-04-arm64-1-core-4-ram
    timeout-minutes: 1
    outputs:
      match: ${{ steps.tag-check.outputs.match }}
    steps:
      - id: tag-check
        run: |
          if [[ " ${{ inputs.tag }}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
            echo "valid tag for release"
          else
            echo "match=false" >> $GITHUB_OUTPUT
            echo " ${{ inputs.tag }} is invalid tag for release. Tag check regex: ^([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$"
          fi